services:
    okvpn_migration.db_id_name_generator:
        class: Okvpn\Bundle\MigrationBundle\Tools\DbIdentifierNameGenerator

    okvpn_migration.data_fixtures.loader:
        class: Okvpn\Bundle\MigrationBundle\Migration\Loader\DataFixturesLoader
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    okvpn_migration.migrations.loader:
        class: Okvpn\Bundle\MigrationBundle\Migration\Loader\MigrationsLoader

    okvpn_migration.data_fixtures.executor:
        class: Okvpn\Bundle\MigrationBundle\Migration\DataFixturesExecutor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    okvpn_migration.migrations.loader:
        class: Okvpn\Bundle\MigrationBundle\Migration\Loader\MigrationsLoader
        arguments:
            - '@kernel'
            - '@doctrine.dbal.default_connection'
            - '@service_container'
            - '@event_dispatcher'

    okvpn_migration.migrations.query_executor:
        class: Okvpn\Bundle\MigrationBundle\Migration\MigrationQueryExecutor
        arguments:
            - '@doctrine.dbal.default_connection'

    okvpn_migration.migrations.executor:
        class: Okvpn\Bundle\MigrationBundle\Migration\MigrationExecutorWithNameGenerator
        arguments:
            - '@okvpn_migration.migrations.query_executor'
        calls:
            - [setExtensionManager, ['@okvpn_migration.migrations.extension_manager']]
            - [setNameGenerator, ['@okvpn_migration.db_id_name_generator']]

    okvpn_migration.migration.pre_up.listener:
        class: Okvpn\Bundle\MigrationBundle\EventListener\PreUpMigrationListener
        tags:
            - { name: kernel.event_listener, event: okvpn_migration.pre_up, method: onPreUp }

    okvpn_migration.migrations.extension_manager:
        class: Okvpn\Bundle\MigrationBundle\Migration\MigrationExtensionManager

    okvpn_migration.migration.extension.rename:
        class: Okvpn\Bundle\MigrationBundle\Migration\Extension\RenameExtension
        tags:
            - { name: okvpn_migration.extension, extension_name: rename }

    okvpn_migration.migration.extension.data_storage:
        class: Okvpn\Bundle\MigrationBundle\Migration\Extension\DataStorageExtension
        tags:
            - { name: okvpn_migration.extension, extension_name: data_store }

    okvpn_migration.tools.schema_dumper:
        class: Okvpn\Bundle\MigrationBundle\Tools\SchemaDumper
        arguments:
            - '@twig'

    okvpn_migration.twig.schema_dumper:
        class: Okvpn\Bundle\MigrationBundle\Twig\SchemaDumperExtension
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension }

    okvpn_migration.listener.console_command_listener:
        class: Okvpn\Bundle\MigrationBundle\EventListener\ConsoleCommandListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
